#!/bin/bash
pushd `dirname $0` > /dev/null
export ERRUBY_PATH=`pwd`
popd > /dev/null
if [[ $* == *"-f"* ]]
then
escript "${ERRUBY_PATH}/ebin/erruby.beam" $*
else
erl -noshell +P 134217727 -pa ebin -s erruby main "{$*}" -s init stop
fi
